parent dbfaad9e6ce10ab9690b6df31c991ba47be2c0d3 author Max Wittek <wimax@graplsecurity.com> 1631647988 -0700 committer Max Wittek <wimax@graplsecurity.com> 1632347437 -0700
Rename e2e to e2e.build.yml

Attempt: What if I change the vars dicts around

Revert "Attempt: What if I change the vars dicts around"

This reverts commit 786824a8f5e07d11f07efa0f38b54e74ff13fe95.

Reorganize pulumi input variab;es

ok, integ tests still succeed

e2e tests work and are in decent shape; get graph merger hooked up

Data gets as far as Graph Merger, but fails there:

Now has this error
```
...skipping...
thread 'main' panicked at 'Surfaced an error despite retry strategy while performing an upsert.: (Dgraph: gRPC communication Error.

Caused by:
    0: transport error: error trying to connect: tcp connect error: Cannot assign requested address (os error 99)
    1: error trying to connect: tcp connect error: Cannot assign requested address (os error 99)
    2: tcp connect error: Cannot assign requested address (os error 99)
    3: Cannot assign requested address (os error 99), 21)', graph-merger/src/upserter.rs:297:14
stack backtrace:
thread 'main' panicked at 'Surfaced an error despite retry strategy while performing an upsert.: (Dgraph: gRPC communication Error.

Caused by:
    0: transport error: error trying to connect: tcp connect error: Cannot assign requested address (os error 99)
    1: error trying to connect: tcp connect error: Cannot assign requested address (os error 99)
    2: tcp connect error: Cannot assign requested address (os error 99)
    3: Cannot assign requested address (os error 99), 21)', graph-merger/src/upserter.rs:297:14
stack backtrace:
   0: rust_begin_unwind
```

Remove grapl-network stuff; e2e now works all the way up to analyzer executor inclusive

Reupgrade engagement creator to a docker image

ugh connect man

Oh god. I just discovered I have to move it to push, not pull.

Move sqs stuff to grapl-common. Begin preparing engagement-creator for de-lambdification

revert lambdas dockerfile

Move event_retriever to grapl common

Remove pulumi engagement creator

Okay engagement creator packaging is correct now

Engagement Creator now has a dedicated run

I'm almost there, just wanna simplify graplcommon

Refactor grapl-common BUILDs

Okay it works hahahaha

format

Copy over the parse/download from analyzer executor