E2E tests in Nomad (awaiting Actix Service) (#1173)
* e2e in nomad started

Oh shoot theres a bug

An attempt at e2e. Only one job per file tho

Separate e2e stuff to a separate jobspec

It gets up to trying to hit Engagement Edge

* parent dbfaad9e6ce10ab9690b6df31c991ba47be2c0d3
author Max Wittek <wimax@graplsecurity.com> 1631647988 -0700
committer Max Wittek <wimax@graplsecurity.com> 1632347437 -0700

Rename e2e to e2e.build.yml

Attempt: What if I change the vars dicts around

Revert "Attempt: What if I change the vars dicts around"

This reverts commit 786824a8f5e07d11f07efa0f38b54e74ff13fe95.

Reorganize pulumi input variab;es

ok, integ tests still succeed

e2e tests work and are in decent shape; get graph merger hooked up

Data gets as far as Graph Merger, but fails there:

Now has this error
```
...skipping...
thread 'main' panicked at 'Surfaced an error despite retry strategy while performing an upsert.: (Dgraph: gRPC communication Error.

Caused by:
    0: transport error: error trying to connect: tcp connect error: Cannot assign requested address (os error 99)
    1: error trying to connect: tcp connect error: Cannot assign requested address (os error 99)
    2: tcp connect error: Cannot assign requested address (os error 99)
    3: Cannot assign requested address (os error 99), 21)', graph-merger/src/upserter.rs:297:14
stack backtrace:
thread 'main' panicked at 'Surfaced an error despite retry strategy while performing an upsert.: (Dgraph: gRPC communication Error.

Caused by:
    0: transport error: error trying to connect: tcp connect error: Cannot assign requested address (os error 99)
    1: error trying to connect: tcp connect error: Cannot assign requested address (os error 99)
    2: tcp connect error: Cannot assign requested address (os error 99)
    3: Cannot assign requested address (os error 99), 21)', graph-merger/src/upserter.rs:297:14
stack backtrace:
   0: rust_begin_unwind
```

Remove grapl-network stuff; e2e now works all the way up to analyzer executor inclusive

Reupgrade engagement creator to a docker image

ugh connect man

Oh god. I just discovered I have to move it to push, not pull.

Move sqs stuff to grapl-common. Begin preparing engagement-creator for de-lambdification

revert lambdas dockerfile

Move event_retriever to grapl common

Remove pulumi engagement creator

Okay engagement creator packaging is correct now

Engagement Creator now has a dedicated run

I'm almost there, just wanna simplify graplcommon

Refactor grapl-common BUILDs

Okay it works hahahaha

format

Copy over the parse/download from analyzer executor

* Port engagement-creator from a Lambda to a service-that-retrieves-events (#1186)

* Reupgrade engagement creator to a docker image

* ugh connect man

* Oh god. I just discovered I have to move it to push, not pull.

* Move sqs stuff to grapl-common. Begin preparing engagement-creator for de-lambdification

* revert lambdas dockerfile

* Move event_retriever to grapl common

* Remove pulumi engagement creator

* Okay engagement creator packaging is correct now

* Engagement Creator now has a dedicated run

* I'm almost there, just wanna simplify graplcommon

* Refactor grapl-common BUILDs

* Okay it works hahahaha

* format

* remove some newlines

* Remove duplicate engagement creator

* Okay I think i got the typecheck stuff working

* ugh python packaging sucks. fixed it.

* Almost works except NoSuchKey thing

* What if i do the replace thing

* Grapl web ui now 403s for user not found

* Clean up nomad artifacts a bit, less sha garbage

* All e2e tests work hahaha

* What if i add an or or true

* Attempting a graplctl await-provision command

* detach=false on nomad job deploys, so pulumi knows if something failed deployment

* format

* Remove graplctl await-provision; the new Nomad detach=false does the trick for us.

* Dump task statuses as an artifact

* ugh, made it a property

* Dump should work now

* About to pull provisioner into another group

* I give up on current attempt; going to do provision as its own job

* Okay, it finally works on my laptop and I have dependencies set up so provision happens after dgraph is up

* Clean up some stuff