Update tool lockfiles
However, we're _not_ updating `black.lockfile` because we were seeing
a lot of

```
ImportError: cannot import name '_unicodefun' from 'click'
```

when invoking Black.

Signed-off-by: Christopher Maier <chris@graplsecurity.com>